language: generic # don't install any environment

before_install:
 - openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv -in ci/id_rsa.enc -out ~/.ssh/id_rsa -d
 - chmod 600 ~/.ssh/id_rsa
script:
 - bash ./ci/build.sh
 - bash ./ci/publish.sh
